---
# TODO: test DryRun capacity reservation

- name: Create on-demand capacity reservations and save result
  set_fact:
    agnosticd_aws_capacity_reservation_results: >-
      {{ lookup(
      'agnosticd_aws_create_capacity_reservations',
      agnosticd_aws_capacity_reservation,
      ttl=agnosticd_aws_capacity_reservation_ttl
      )
      }}
  changed_when: true

- debug:
    var: agnosticd_aws_capacity_reservation_results

- name: Set AZ and region
  set_fact:
    aws_region: "{{ agnosticd_aws_capacity_reservation_results.region }}"

- name: Ensure aws_region is not passed as extra vars and different
  assert:
    that: aws_region == agnosticd_aws_capacity_reservation_results.region
    msg: >-
      If you want to use on-demand capacity reservations, do not set
      aws_region as extra-vars.

- name: Set default aws_availability_zone (single AZ)
  when: agnosticd_aws_capacity_reservation_results.single_availability_zone | default('') != ''
  set_fact:
    aws_availability_zone: "{{ agnosticd_aws_capacity_reservation_results.single_availability_zone }}"

