---
# TODO: test DryRun capacity reservation

- name: Create on-demand capacity reservations and save result
  set_fact:
    _capacity_reservations: >-
      {{ lookup(
      'agnosticd_aws_create_capacity_reservations',
      agnosticd_aws_capacity_reservation,
      ttl=agnosticd_aws_capacity_reservation_ttl
      )
      }}

- name: Set AZ and region
  set_fact:
    aws_region: "{{ _capacity_reservations.region }}"
    aws_availability_zones: "{{ _capacity_reservations.azs }}"

- name: Set capacity reservation IDs if any
  when: _capacity_reservations.ids | default([]) | length > 0
  set_fact:
    aws_capacity_reservation_ids: "{{ _capacity_reservations.ids }}"

# TODO: Remove
- fail:
