---
- name: Ensure mandatory variables are set
  assert:
    that: "{{ check.that }}"
    fail_msg: "{{ check.msg }}"
    quiet: true
  loop_control:
    loop_var: check
    label: "{{ check.msg }}"
  loop:
    - msg: reservations are missing in agnosticd_aws_capacity_reservation dictionary
      that: agnosticd_aws_capacity_reservation.reservations | default([]) | length > 0

    - msg: regions are missing in agnosticd_aws_capacity_reservation dictionary
      that: agnosticd_aws_capacity_reservation.regions | default([]) | length > 0
