---
# sample configuration file
#
# Usage: ansible-playbook main.yml -e @configs/just-a-bunch-of-nodes/sample.yml
#
# Ideally keep your copy OUTSIDE your repo, especially if using Cloud Credentials

env_type: just-a-bunch-of-nodes       # Name of config to deploy
output_dir: /tmp/workdir                # Writable working scratch directory
node_instance_count: 2                  # Number of nodes to deploy
node_instance_type: m5.xlarge           # instance type
email: name@example.com                 # User info for notifications

guid: guid02                             # Unique string used in FQDN
subdomain_base_suffix: .example.opentlc.com      # Your domain used in FQDN

# Path to yum repos
own_repo_path: http://admin.example.com/repos/version

# Cloud specfic settings - example given here for AWS

cloud_provider: ec2                     # Which AgnosticD Cloud Provider to use
aws_region: us-east-1                   # AWS Region to deploy in
HostedZoneId: Z3IHLWJZOU9SRT            # You will need to change this
key_name: ocpkey                        # Keyname must exist in AWS

# AWS Credentials. These are required (don't sync them to your fork)
# aws_access_key_id:
# aws_secret_access_key:
#

# AWS on-demand capacity reservation
agnosticd_aws_capacity_reservation:
  regions:
  - "ap-southeast-1"
  - "us-east-2"
  - "{{ aws_region }}"
  - "eu-west-2"
  reservations:
    az1:
      - instance_count: "{{ node_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "a1.xlarge"
      - instance_count: "{{ node_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "{{ node_instance_type }}"
      - instance_count: "{{ node_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "m5.xlarge"
      - instance_count: 20
        instance_platform: Linux/UNIX
        instance_type: "m5a.8xlarge"
    az2:
      - instance_count: 10
        instance_platform: Linux/UNIX
        instance_type: "m5a.4xlarge"
      - instance_count: "{{ node_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "c5.large"
      - instance_count: "{{ node_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "m4.4xlarge"
      - instance_count: "{{ node_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "m5zn.large"
      - instance_count: 2
        instance_platform: Linux/UNIX
        instance_type: "m6g.xlarge"
      - instance_count: 2
        instance_platform: Linux/UNIX
        instance_type: "m5n.large"
...
